/**
 * @license
 *
 * Copyright IBM Corp. 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { STYLE_PICKER_ALIGNMENT } from '../defs';

export const alignOptions = [
  STYLE_PICKER_ALIGNMENT.TOP,
  STYLE_PICKER_ALIGNMENT.TOP_LEFT,
  STYLE_PICKER_ALIGNMENT.TOP_RIGHT,
  STYLE_PICKER_ALIGNMENT.BOTTOM,
  STYLE_PICKER_ALIGNMENT.BOTTOM_LEFT,
  STYLE_PICKER_ALIGNMENT.BOTTOM_RIGHT,
  STYLE_PICKER_ALIGNMENT.LEFT,
  STYLE_PICKER_ALIGNMENT.LEFT_BOTTOM,
  STYLE_PICKER_ALIGNMENT.LEFT_TOP,
  STYLE_PICKER_ALIGNMENT.RIGHT,
  STYLE_PICKER_ALIGNMENT.RIGHT_BOTTOM,
  STYLE_PICKER_ALIGNMENT.RIGHT_TOP,
];
