name: Deploy storybook to S3 (production)
run-name: Publish ${{ inputs.tag }} to Production by @${{ github.actor }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Specify the tag for this release (ie. v0.0.1-rc.0)'
        type: string

jobs:
  build:
    if: github.repository == 'carbon-design-system/carbon-for-ai'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install pnpm
        run: npm install -g pnpm@8

      - name: Install dependencies
        run: pnpm install

      - name: Build storybook
        run: pnpm build-storybook

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.C4AI_COS_BUCKET_PRODUCTION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.C4AI_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.C4AI_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.C4AI_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.C4AI_COS_ENDPOINT }}
          SOURCE_DIR: 'storybook-static'
