name: Deploy storybook to S3 (production)
run-name: Publish to Production by @${{ github.actor }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-latest-storybook]

jobs:
  web-components:
    if: github.repository == 'carbon-design-system/carbon-labs'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'packages/web-components'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build storybook
        run: npx storybook build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.CLABS_COS_BUCKET_PRODUCTION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CLABS_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLABS_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.CLABS_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.CLABS_COS_ENDPOINT }}
          SOURCE_DIR: 'storybook-static'
